# Type stubs for the PyO3 module (crates/circuit-core-py/src/lib.rs).
# Result strings are JSON shaped {"ok": ...} | {"err": ...}; see contract/schema/.

class Registry:
    @staticmethod
    def from_json(bundle: str) -> Registry: ...
    @staticmethod
    def from_yaml_docs(version: str, docs: list[tuple[str, str]], symbols: list[tuple[str, str]]) -> Registry: ...
    @property
    def version(self) -> str: ...
    def to_json(self) -> str: ...
    def part_ids(self) -> list[str]: ...

class Session:
    def __init__(self, registry: Registry, snapshot: str | None = None) -> None: ...
    def apply(self, envelope: str) -> str: ...
    def apply_ops(self, ops: str, author: str) -> str: ...
    def apply_all(self, envelopes: str) -> str: ...
    def erc(self, ctx: str, scope: str | None = None) -> str: ...
    def compile(self, opts: str = "{}") -> str: ...
    def changes(self, patch: str) -> str: ...
    def next_refdes(self, part: str) -> str: ...
    def connect(self, from_pin: str, to: str) -> str: ...
    def snapshot(self) -> str: ...
    def circuit_text(self) -> str: ...
    @property
    def rev(self) -> int: ...
    def fork(self) -> Session: ...

def parse_quantity(text: str, unit: str) -> str: ...
def core_version() -> str: ...
