//! JSON Schemas for every wire type. Written to `contract/schema/` by
//! `cargo run -p circuit-core --example export_schema`; the TS and Pydantic types are generated
//! from `contract.schema.json` (every type under `$defs`), and CI fails if anything drifts
//! (`tests/contract.rs`).

use schemars::generate::SchemaSettings;
use schemars::{JsonSchema, schema_for};
use serde_json::{Value, json};

use crate::apply::{Patch, Trial};
use crate::edit::WireEnd;
use crate::erc::{ErcContext, ErcIssue};
use crate::error::OpError;
use crate::ir::Circuit;
use crate::ops::OpEnvelope;
use crate::registry::Registry;
use crate::session::json_api::Outcome;
use crate::session::{ApplyOk, PatchData};
use crate::spice::{CompileError, CompileOpts, Netlist};

/// `(file name, schema)` for each contract type, in a fixed order.
pub fn all_schemas() -> Vec<(&'static str, Value)> {
    fn v(s: schemars::Schema) -> Value {
        s.to_value()
    }
    vec![
        ("circuit.schema.json", v(schema_for!(Circuit))),
        ("op_envelope.schema.json", v(schema_for!(OpEnvelope))),
        ("op_error.schema.json", v(schema_for!(OpError))),
        ("patch.schema.json", v(schema_for!(Patch))),
        ("erc_issue.schema.json", v(schema_for!(ErcIssue))),
        ("netlist.schema.json", v(schema_for!(Netlist))),
        ("compile_error.schema.json", v(schema_for!(CompileError))),
        ("registry.schema.json", v(schema_for!(Registry))),
        ("compile_opts.schema.json", v(schema_for!(CompileOpts))),
        ("apply_result.schema.json", v(schema_for!(Outcome<ApplyOk, OpError>))),
        ("patch_data.schema.json", v(schema_for!(PatchData))),
        ("trial.schema.json", v(schema_for!(Trial))),
        ("contract.schema.json", contract_schema()),
    ]
}

/// Every contract type in one schema, under `$defs`: the single input for TS/Pydantic codegen,
/// so shared types (Circuit, Op, ...) are generated once.
pub fn contract_schema() -> Value {
    let mut generator = SchemaSettings::draft2020_12().into_generator();
    fn add<T: JsonSchema>(g: &mut schemars::SchemaGenerator) {
        g.subschema_for::<T>();
    }
    add::<Circuit>(&mut generator);
    add::<OpEnvelope>(&mut generator);
    add::<OpError>(&mut generator);
    add::<Patch>(&mut generator);
    add::<ApplyOk>(&mut generator);
    add::<Outcome<ApplyOk, OpError>>(&mut generator);
    add::<PatchData>(&mut generator);
    add::<Trial>(&mut generator);
    add::<ErcContext>(&mut generator);
    add::<ErcIssue>(&mut generator);
    add::<CompileOpts>(&mut generator);
    add::<Netlist>(&mut generator);
    add::<CompileError>(&mut generator);
    add::<Registry>(&mut generator);
    add::<WireEnd>(&mut generator);
    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Contract",
        "description": "All circuit-core wire types. Generated by circuit-core; do not edit.",
        "$defs": generator.definitions(),
    })
}

/// Pretty JSON with a trailing newline, so committed files are stable across platforms.
pub fn render(schema: &Value) -> String {
    let mut s = serde_json::to_string_pretty(schema).expect("schema serializes");
    s.push('\n');
    s
}
