# Generated from contract/schema/contract.schema.json by tools/codegen. Do not edit.

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Contract(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description="All circuit-core wire types. Generated by circuit-core; do not edit.",
            title="Contract",
        ),
    ]


class Unit(StrEnum):
    ohm = "ohm"
    farad = "farad"
    henry = "henry"
    volt = "volt"
    ampere = "ampere"
    hertz = "hertz"
    second = "second"
    watt = "watt"
    unitless = "unitless"


class Origin1(BaseModel):
    job_id: str
    kind: Literal["llm"]


class Origin2(BaseModel):
    kind: Literal["user"]


class Origin3(BaseModel):
    id: str
    kind: Literal["template"]


class Origin(RootModel[Origin1 | Origin2 | Origin3]):
    root: Origin1 | Origin2 | Origin3


class Placement(BaseModel):
    x: float
    y: float
    rot: Annotated[
        int | None, Field(description="Degrees: 0, 90, 180 or 270.", ge=0, le=65535)
    ] = 0
    flip: bool | None = False


class PinRef(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Part pin as REFDES.PIN, e.g. "R3.1" or "U1.OUT_A".',
            pattern="^[A-Za-z0-9_]+\\.[A-Za-z0-9_]+$",
        ),
    ]


class NetKind1(BaseModel):
    kind: Literal["signal"]


class NetKind2(BaseModel):
    volts: float
    kind: Literal["power"]


class NetKind3(BaseModel):
    kind: Literal["ground"]


class NetKind(RootModel[NetKind1 | NetKind2 | NetKind3]):
    root: NetKind1 | NetKind2 | NetKind3


class BlockRole(StrEnum):
    supply = "supply"
    source = "source"
    bias = "bias"
    amplifier = "amplifier"
    buffer = "buffer"
    filter = "filter"
    oscillator = "oscillator"
    comparator = "comparator"
    load = "load"
    other = "other"


class SpecTarget(BaseModel):
    target: float
    tol_pct: float


class PortDirection(StrEnum):
    input = "input"
    output = "output"
    bidir = "bidir"
    power_pos = "power_pos"
    power_neg = "power_neg"
    ground = "ground"


class BlockStatus(StrEnum):
    planned = "planned"
    composing = "composing"
    verified = "verified"
    committed = "committed"
    failed = "failed"


class Analysis1(BaseModel):
    type: Literal["op"]


class Analysis2(BaseModel):
    source: str
    start: float
    stop: float
    step: float
    type: Literal["dc"]


class Analysis3(BaseModel):
    points_per_decade: Annotated[int, Field(ge=0)]
    f_start: float
    f_stop: float
    type: Literal["ac"]


class Analysis4(BaseModel):
    t_step: float
    t_stop: float
    type: Literal["tran"]


class Analysis(RootModel[Analysis1 | Analysis2 | Analysis3 | Analysis4]):
    root: Analysis1 | Analysis2 | Analysis3 | Analysis4


class LayoutHint2(BaseModel):
    a: str
    b: str
    kind: Literal["near"]


class LayoutHint3(BaseModel):
    block: str
    kind: Literal["group"]


class Direction(StrEnum):
    right = "right"
    down = "down"


class BlockRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str


class BlockAbort(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    reason: str


class BlockSetStatus(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    status: BlockStatus


class PartAdd(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    refdes: str
    part: str
    params: Annotated[
        dict[str, str] | None,
        Field(
            description='Values as written ("10k", "4.7u"); unspecified params take the registry default.'
        ),
    ] = {}
    block: str | None = None
    origin: Annotated[
        Origin | None,
        Field(
            description="Normally derived from the envelope; set explicitly by inverse ops so undo restores it."
        ),
    ] = None


class PartRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    refdes: str


class PartSetParam(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    refdes: str
    key: str
    value: str


class PartSwap(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    refdes: str
    part: str


class PartPin(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    refdes: str
    placement: Placement | None = None


class NetConnect(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    net: str
    pins: list[PinRef]
    kind: Annotated[
        NetKind | None,
        Field(
            description="Applied when the net is created; must match if the net exists."
        ),
    ] = None
    label: str | None = None


class NetDisconnect(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    net: str
    pins: list[PinRef]


class NetRename(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: Annotated[str, Field(alias="from")]
    to: str


class AnalysisSet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    analyses: list[Analysis]


class Narrate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    refs: list[str]
    text: str
    block: str | None = None


class Author(StrEnum):
    llm = "llm"
    user = "user"
    template = "template"


class ErrorCode1(StrEnum):
    """
    Error codes returned by `apply()`. These go back to the LLM verbatim during repair and are
    shown to users as friendly text (LLD §4). Additive only within a protocol major version.
    """

    part_not_in_registry = "part_not_in_registry"
    pin_not_found = "pin_not_found"
    pin_already_connected = "pin_already_connected"
    param_out_of_range = "param_out_of_range"
    refdes_conflict = "refdes_conflict"
    block_not_open = "block_not_open"
    stale_rev = "stale_rev"
    unknown_op = "unknown_op"
    limit_exceeded = "limit_exceeded"
    part_not_found = "part_not_found"
    param_unknown = "param_unknown"
    net_not_found = "net_not_found"
    block_not_found = "block_not_found"
    block_conflict = "block_conflict"
    hint_not_found = "hint_not_found"


class ErrorCode(
    RootModel[
        ErrorCode1
        | Literal["schema_error"]
        | Literal["unsupported_version"]
        | Literal["registry_mismatch"]
        | Literal["refdes_invalid"]
        | Literal["bad_value"]
        | Literal["category_mismatch"]
        | Literal["net_invalid"]
        | Literal["net_conflict"]
        | Literal["block_not_empty"]
        | Literal["analysis_invalid"]
        | Literal["forbidden"]
    ]
):
    root: Annotated[
        ErrorCode1
        | Literal["schema_error"]
        | Literal["unsupported_version"]
        | Literal["registry_mismatch"]
        | Literal["refdes_invalid"]
        | Literal["bad_value"]
        | Literal["category_mismatch"]
        | Literal["net_invalid"]
        | Literal["net_conflict"]
        | Literal["block_not_empty"]
        | Literal["analysis_invalid"]
        | Literal["forbidden"],
        Field(
            description="Error codes returned by `apply()`. These go back to the LLM verbatim during repair and are\nshown to users as friendly text (LLD §4). Additive only within a protocol major version."
        ),
    ]


class Patch(BaseModel):
    """
    What changed, by id, so the UI never needs the whole circuit per op (LLD §10).
    """

    parts_upserted: list[str]
    parts_removed: list[str]
    nets_upserted: list[str]
    nets_removed: list[str]
    blocks_upserted: list[str]
    blocks_removed: list[str]
    analyses_changed: bool
    hints_changed: bool


class ErcContext(StrEnum):
    """
    Who the check is for: LLM blocks must be clean; learners may build broken circuits.
    """

    llm_block = "llm_block"
    user_edit = "user_edit"


class ErcCode(StrEnum):
    floating_pin = "floating_pin"
    dangling_net = "dangling_net"
    no_dc_path = "no_dc_path"
    vsource_loop = "vsource_loop"
    unpowered_ic = "unpowered_ic"
    output_conflict = "output_conflict"
    supply_short = "supply_short"
    over_voltage = "over_voltage"
    port_unbound = "port_unbound"
    unused_unit = "unused_unit"


class Severity1(StrEnum):
    warning = "warning"
    info = "info"


class Severity(RootModel[Severity1 | Literal["error"]]):
    root: Severity1 | Literal["error"]


class CompileOpts(BaseModel):
    shunt_floating: Annotated[
        bool | None,
        Field(
            description="Add a 1 GΩ shunt to ground on every node without a DC path (user circuits, ERC003),\nso the simulation still runs and the tutor can explain the problem."
        ),
    ] = False
    analyses: Annotated[
        list[Analysis] | None,
        Field(
            description="Override the circuit's analyses (e.g. the interactive default). `None` uses\n`circuit.analyses`, or `.op` if that is empty."
        ),
    ] = None


class MeasDef(BaseModel):
    name: str
    line: str


class CompileError(BaseModel):
    refdes: str | None = None
    message: str


class Category(StrEnum):
    R = "R"
    C = "C"
    L = "L"
    D = "D"
    Q = "Q"
    U = "U"
    V = "V"
    J = "J"


class PinType1(StrEnum):
    input = "input"
    output = "output"
    passive = "passive"
    power_pos = "power_pos"
    power_neg = "power_neg"


class PinType(RootModel[PinType1 | Literal["nc"]]):
    root: PinType1 | Literal["nc"]


class ParamDef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    unit: Unit
    default: str
    min: Annotated[
        float | None,
        Field(
            description="In SI units. YAML sources may write a prefixed number such as `1p` or `100meg`."
        ),
    ] = None
    max: float | None = None


class SpiceDef(BaseModel):
    """
    SPICE emission template. `line` is for single-unit parts; `unit_line` is emitted once per
    used unit of a multi-unit part. Placeholders: `{refdes}`, `{unit}`, pin names, param names.
    In `unit_line`, a unit pin is named without its `_<unit>` suffix (`{OUT}` → `OUT_A`).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    include: str | None = None
    line: str | None = None
    unit_line: str | None = None


class Hazard(StrEnum):
    mains = "mains"


class Side(StrEnum):
    left = "left"
    right = "right"
    top = "top"
    bottom = "bottom"


class Quantity(BaseModel):
    """
    A parsed physical value. `display` is canonical and round-trips exactly through [`parse_quantity`].
    """

    si: float
    unit: Unit
    display: str


class Net(BaseModel):
    id: str
    pins: list[PinRef]
    kind: NetKind
    label: str | None = None


class BlockPort(BaseModel):
    """
    A named interface of a block, bound to the net that carries it (checked by ERC009).
    """

    name: str
    direction: PortDirection
    net: str


class LayoutHint1(BaseModel):
    dir: Direction
    kind: Literal["flow"]


class LayoutHint(RootModel[LayoutHint1 | LayoutHint2 | LayoutHint3]):
    root: LayoutHint1 | LayoutHint2 | LayoutHint3


class OpEnvelope2(BaseModel):
    op: Literal["block.commit"]
    body: BlockRef


class OpEnvelope3(BaseModel):
    op: Literal["block.abort"]
    body: BlockAbort


class OpEnvelope4(BaseModel):
    """
    Inverse of `block.begin`.
    """

    op: Literal["block.remove"]
    body: BlockRef


class OpEnvelope5(BaseModel):
    """
    Inverse of `block.commit` / `block.abort`.
    """

    op: Literal["block.set_status"]
    body: BlockSetStatus


class OpEnvelope6(BaseModel):
    op: Literal["part.add"]
    body: PartAdd


class OpEnvelope7(BaseModel):
    op: Literal["part.remove"]
    body: PartRef


class OpEnvelope8(BaseModel):
    op: Literal["part.set_param"]
    body: PartSetParam


class OpEnvelope9(BaseModel):
    op: Literal["part.swap"]
    body: PartSwap


class OpEnvelope10(BaseModel):
    op: Literal["part.pin"]
    body: PartPin


class OpEnvelope11(BaseModel):
    op: Literal["net.connect"]
    body: NetConnect


class OpEnvelope12(BaseModel):
    op: Literal["net.disconnect"]
    body: NetDisconnect


class OpEnvelope13(BaseModel):
    op: Literal["net.rename"]
    body: NetRename


class OpEnvelope14(BaseModel):
    op: Literal["analysis.set"]
    body: AnalysisSet


class OpEnvelope17(BaseModel):
    op: Literal["narrate"]
    body: Narrate


class OpEnvelope18(BaseModel):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """

    v: Annotated[int, Field(ge=0, le=65535)]
    seq: Annotated[int, Field(ge=0)]
    author: Author
    job: str | None = None
    block: str | None = None
    base_rev: Annotated[int, Field(ge=0)]


class OpEnvelope20(OpEnvelope2, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope21(OpEnvelope3, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope22(OpEnvelope4, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope23(OpEnvelope5, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope24(OpEnvelope6, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope25(OpEnvelope7, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope26(OpEnvelope8, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope27(OpEnvelope9, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope28(OpEnvelope10, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope29(OpEnvelope11, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope30(OpEnvelope12, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope31(OpEnvelope13, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope32(OpEnvelope14, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope35(OpEnvelope17, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class Op2(BaseModel):
    op: Literal["block.commit"]
    body: BlockRef


class Op3(BaseModel):
    op: Literal["block.abort"]
    body: BlockAbort


class Op4(BaseModel):
    """
    Inverse of `block.begin`.
    """

    op: Literal["block.remove"]
    body: BlockRef


class Op5(BaseModel):
    """
    Inverse of `block.commit` / `block.abort`.
    """

    op: Literal["block.set_status"]
    body: BlockSetStatus


class Op6(BaseModel):
    op: Literal["part.add"]
    body: PartAdd


class Op7(BaseModel):
    op: Literal["part.remove"]
    body: PartRef


class Op8(BaseModel):
    op: Literal["part.set_param"]
    body: PartSetParam


class Op9(BaseModel):
    op: Literal["part.swap"]
    body: PartSwap


class Op10(BaseModel):
    op: Literal["part.pin"]
    body: PartPin


class Op11(BaseModel):
    op: Literal["net.connect"]
    body: NetConnect


class Op12(BaseModel):
    op: Literal["net.disconnect"]
    body: NetDisconnect


class Op13(BaseModel):
    op: Literal["net.rename"]
    body: NetRename


class Op14(BaseModel):
    op: Literal["analysis.set"]
    body: AnalysisSet


class Op17(BaseModel):
    op: Literal["narrate"]
    body: Narrate


class BlockBegin(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    role: BlockRole
    title: str
    spec: Annotated[dict[str, SpecTarget] | None, Field(validate_default=True)] = {}
    ports: Annotated[list[BlockPort] | None, Field(validate_default=True)] = []
    template: str | None = None


class HintBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    hint: LayoutHint


class OpError(BaseModel):
    code: ErrorCode
    message: str
    op_index: Annotated[
        int | None,
        Field(
            description="Index of the failing op within a batch (`apply_all`).", ge=0
        ),
    ] = None


class Outcome2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    err: OpError


class ErcIssue(BaseModel):
    rule: str
    code: ErcCode
    severity: Severity
    message: str
    parts: list[str] | None = None
    nets: list[str] | None = None
    pins: list[PinRef] | None = None
    block: str | None = None


class Netlist(BaseModel):
    text: Annotated[
        str, Field(description="Deterministic: parts in natural refdes order.")
    ]
    hash: Annotated[str, Field(description="Lowercase hex sha256 of `text`.")]
    node_map: Annotated[
        dict[str, str],
        Field(
            description='IR net id -> SPICE node name ("N_VOUT" -> "n_vout", "GND" -> "0").'
        ),
    ]
    includes: Annotated[
        list[str],
        Field(
            description="Registry model files the simulator must load, relative to the registry root."
        ),
    ]
    meas: Annotated[
        list[MeasDef],
        Field(
            description="Spec checks as `.meas` statements (filled once block templates define them)."
        ),
    ]


class PinDef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    num: Annotated[int, Field(ge=0, le=65535)]
    type: PinType
    unit: str | None = None


class Anchor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: Annotated[int, Field(ge=0)]
    y: Annotated[int, Field(ge=0)]
    side: Annotated[
        Side,
        Field(
            description="The edge the anchor sits on; wires leave the symbol in this direction."
        ),
    ]


class PartInstance(BaseModel):
    refdes: str
    part: str
    params: Annotated[
        dict[str, Quantity],
        Field(
            description='Every param declared by the registry part, keyed by name ("resistance" -> 10kΩ).'
        ),
    ]
    block: str | None = None
    origin: Origin
    pinned: Placement | None = None


class Block(BaseModel):
    id: str
    role: BlockRole
    title: str
    spec: dict[str, SpecTarget]
    ports: list[BlockPort]
    status: BlockStatus
    template: str | None = None


class OpEnvelope1(BaseModel):
    op: Literal["block.begin"]
    body: BlockBegin


class OpEnvelope15(BaseModel):
    op: Literal["hint.add"]
    body: HintBody


class OpEnvelope16(BaseModel):
    """
    Inverse of `hint.add`.
    """

    op: Literal["hint.remove"]
    body: HintBody


class OpEnvelope19(OpEnvelope1, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope33(OpEnvelope15, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope34(OpEnvelope16, OpEnvelope18):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """


class OpEnvelope(
    RootModel[
        OpEnvelope19
        | OpEnvelope20
        | OpEnvelope21
        | OpEnvelope22
        | OpEnvelope23
        | OpEnvelope24
        | OpEnvelope25
        | OpEnvelope26
        | OpEnvelope27
        | OpEnvelope28
        | OpEnvelope29
        | OpEnvelope30
        | OpEnvelope31
        | OpEnvelope32
        | OpEnvelope33
        | OpEnvelope34
        | OpEnvelope35
    ]
):
    """
    One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`.
    """

    root: Annotated[
        OpEnvelope19
        | OpEnvelope20
        | OpEnvelope21
        | OpEnvelope22
        | OpEnvelope23
        | OpEnvelope24
        | OpEnvelope25
        | OpEnvelope26
        | OpEnvelope27
        | OpEnvelope28
        | OpEnvelope29
        | OpEnvelope30
        | OpEnvelope31
        | OpEnvelope32
        | OpEnvelope33
        | OpEnvelope34
        | OpEnvelope35,
        Field(
            description="One op in its envelope (LLD §4): `{v, seq, op, author, job?, block?, base_rev, body}`."
        ),
    ]


class Op1(BaseModel):
    op: Literal["block.begin"]
    body: BlockBegin


class Op15(BaseModel):
    op: Literal["hint.add"]
    body: HintBody


class Op16(BaseModel):
    """
    Inverse of `hint.add`.
    """

    op: Literal["hint.remove"]
    body: HintBody


class Op(
    RootModel[
        Op1
        | Op2
        | Op3
        | Op4
        | Op5
        | Op6
        | Op7
        | Op8
        | Op9
        | Op10
        | Op11
        | Op12
        | Op13
        | Op14
        | Op15
        | Op16
        | Op17
    ]
):
    root: (
        Op1
        | Op2
        | Op3
        | Op4
        | Op5
        | Op6
        | Op7
        | Op8
        | Op9
        | Op10
        | Op11
        | Op12
        | Op13
        | Op14
        | Op15
        | Op16
        | Op17
    )


class ApplyOk(BaseModel):
    """
    What a successful `apply` reports to the UI: only what changed (LLD §10).
    """

    rev: Annotated[int, Field(ge=0)]
    patch: Patch
    inverse: Annotated[
        list[Op],
        Field(
            description="Ops that undo this change, in the order they must be applied."
        ),
    ]


class Outcome1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ok: ApplyOk


class Outcome(RootModel[Outcome1 | Outcome2]):
    root: Outcome1 | Outcome2


class PatchData(BaseModel):
    """
    The current state of everything a [`Patch`] names, so a UI mirror can update itself without
    reading the whole circuit (LLD §10). Removed ids are in the patch itself.
    """

    rev: Annotated[int, Field(ge=0)]
    parts: dict[str, PartInstance]
    nets: dict[str, Net]
    blocks: dict[str, Block]
    analyses: Annotated[
        list[Analysis] | None,
        Field(description="Present when `patch.analyses_changed`."),
    ] = None
    hints: Annotated[
        list[LayoutHint] | None,
        Field(description="Present when `patch.hints_changed`."),
    ] = None


class PartDef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    category: Category
    title: str
    role_tags: list[str] | None = []
    units: Annotated[
        list[str] | None,
        Field(
            description="Units of a multi-unit IC (e.g. `[A, B]` for a dual op-amp). Empty for single-unit parts."
        ),
    ] = []
    pins: list[PinDef]
    params: Annotated[
        dict[str, ParamDef] | None,
        Field(
            description="Every param must declare a default, so instances always carry a full param set.",
            validate_default=True,
        ),
    ] = {}
    limits: Annotated[
        dict[str, float] | None,
        Field(
            description="Ratings used by ERC, e.g. `v_supply_max`, `i_max`, `p_max`."
        ),
    ] = {}
    dc_param: Annotated[
        str | None,
        Field(
            description="For voltage sources: the param holding V(P) − V(N) at DC (used by ERC007)."
        ),
    ] = None
    spice: SpiceDef | None = None
    symbol: Annotated[
        str,
        Field(
            description="Schematic symbol, `symbols/<id>.svg`; its pin anchors are matched by pin name."
        ),
    ]
    breadboard: str | None = None
    teach: str | None = None
    hazard: Hazard | None = None


class SymbolDef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    width: Annotated[
        int, Field(description="Size in schematic units (multiples of [`GRID`]).", ge=0)
    ]
    height: Annotated[int, Field(ge=0)]
    pins: Annotated[
        dict[str, Anchor],
        Field(
            description="Pin anchors by pin name (base name for the unit pins of a multi-unit part)."
        ),
    ]


class Circuit(BaseModel):
    schema_version: Annotated[int, Field(ge=0, le=65535)]
    registry_version: str
    rev: Annotated[
        int, Field(description="+1 per applied op (narration excluded).", ge=0)
    ]
    parts: dict[str, PartInstance]
    nets: dict[str, Net]
    blocks: dict[str, Block]
    analyses: list[Analysis]
    hints: Annotated[
        list[LayoutHint],
        Field(
            description="Kept sorted and de-duplicated so the order never depends on edit history."
        ),
    ]


class Trial(BaseModel):
    """
    Outcome of a trial batch (the orchestrator's composer draft).
    """

    circuit: Circuit
    errors: Annotated[
        list[OpError],
        Field(
            description="Every rejected op, with `op_index` set. Rejected ops are skipped; the rest still apply,\nso the LLM gets all its mistakes back in one repair round."
        ),
    ]
    inverse: Annotated[list[Op], Field(description="Undo for the ops that did apply.")]


class Registry(BaseModel):
    version: str
    parts: dict[str, PartDef]
    symbols: Annotated[
        dict[str, SymbolDef],
        Field(
            description="Schematic symbols by id (`symbols/<id>.svg`): geometry only; the drawings ship in the\nbundle's sprite sheet."
        ),
    ]
